class TestExceptions{
	public static void main(String[] args){
		String test  = "Нет";

		try{
			System.out.println("Начало try");
			doRisky(test);
			System.out.println("Конец try");
		}catch(ScaryException se) {
			System.out.println("Жуткое исключение!");
		}finaly{
			System.out.println("finaly");
		}
		System.out.println("Конец main");
	 }
test void doRisky(String test) throws ScaryException{
		System.out.println("Начало опасного метода...");
		if("Да".equals(test)){
			throw new ScaryException();
		}
		System.out.println("Конец опасного метода.");
		return;
	}
}